Microcloud refresh
canonical/canonical.com pull request #1103
Opened 2023-11-01 12:20 UTC by mtruj013

To be merged after all the dev tickets in [this epic](https://warthogs.atlassian.net/browse/WD-6679) are closed

2023-11-01 12:20 UTC, webteam-app commented
Demo starting at https://canonical-com-1103.demos.haus

2023-11-03 10:01 UTC, juanruitina commented
Some comments on mobile after checking with @lyubomir-popov:

- Please hide the icons on mobile only
- The animated command lines are tricky on mobile. Please hide them and replace with a regular snippet, something like this would do:

```html
<div class="p-code-snippet">
  <pre class="p-code-snippet__block--icon  is-wrapped"><code>snap install microcloud lxd microceph microovn</code></pre>
    <pre class="p-code-snippet__block--icon  is-wrapped"><code>microcloud init</code></pre>
</div>
```

It should look like this:

![canonical-com-1103 demos haus_microcloud(Figma mobile) (3)](https://github.com/canonical/canonical.com/assets/1409729/bf036fef-cdb7-4345-ae49-8dbfaff5b43c)

2023-11-06 09:11 UTC, lyubomir-popov commented
Like @juanruitina said, making the animation work on mobile will require extensive breakpoint work - making the text styled as an h2 on big screens, and as a paragraph on smaller screens. I would also propose the simpler fallback - hiding the rich animated piece and using the default code snippet instead.

At he moment: 
- font-size has been overriden, but font weight (and possibly other properties) have not. So it becomes a bit difficult to read paragraph size copy should never be set at a font-weight of 180. 
- Also, the dollar sign remains in h2 size;
also, on smalleer screens the dollar sign is lighter in weight than the rest, and the text jumps in size:


<img width="711" alt="image" src="https://github.com/canonical/canonical.com/assets/2741678/7e187ba4-e46b-4ee1-8b54-6934984cd819">

<img width="546" alt="image" src="https://github.com/canonical/canonical.com/assets/2741678/a74b74d0-1c32-4c29-a862-6a162fbd5c35">

So let's please hide it and use a stock vanilla code snippet on small and medium screens.

2023-11-13 12:35 UTC, anthonydillon commented
We should remove the phone numbers from the contract form. These do not work.

2023-11-13 12:51 UTC, anthonydillon requested changes
Few small comments in the code

2023-11-13 12:51 UTC, anthonydillon commented on templates/microcloud/contact-us.html
> +            <input type="hidden" aria-hidden="true" aria-label="hidden field" name="returnURL" value="https://canonical-com-1102.demos.haus/microcloud/thank-you" />
This is returning to a demo link

2023-11-13 12:51 UTC, anthonydillon commented on static/js/microcloud-slider.js
> +  let resultsCount = document.getElementById('js-results-count');
You should null check these elements are found before continuing in case the mark up changes and js crashes.

2023-11-13 12:51 UTC, anthonydillon commented on templates/microcloud/index.html
> +{% block title %}MicroCloud &ndash; low-touch open source cloud solution{% endblock %}
I believe this should be an `mdash` @lyubomir-popov ?

2023-11-13 12:51 UTC, anthonydillon commented on templates/microcloud/index.html
> +        <a class="p-button--positive" href="https://pages.ubuntu.com/rs/066-EOV-335/images/MicroCloud_Datasheet.pdf">Download the datasheet</a>
Could you add the name of the datasheet here for better SEO and a11y please?

2023-11-13 12:51 UTC, anthonydillon commented on templates/microcloud/index.html
> +{% block meta_copydoc %}https://docs.google.com/document/d/17iBbFCINLYjPBOYWpgoq9SreyYNkR0Sb5jgx5iTo6MA/edit{% endblock meta_copydoc %}
This copy doc seems wrong. It's this the right one?

2023-11-13 17:12 UTC, anthonydillon approved these changes
One last comment in the code.

2023-11-13 17:12 UTC, anthonydillon commented on templates/microcloud/_microcloud-modal.html
> +                <label for="company">Title:</label>
``` suggestion
                <label for="title">Title:</label>
```

2023-11-13 17:34 UTC, merged