Add postgresql page to data bubble and subnav
canonical/canonical.com pull request #1124
Opened 2023-11-23 16:19 UTC by mtruj013

## Done

- Built page as per [doc](https://docs.google.com/document/d/1GxineF4WLt0YlShaYkrzqWjIOkXjLJEfsnUdWVfWnz4/edit) and [design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric-bubble-(rebranding)?node-id=128%3A1198&mode=dev)

## QA

- View the site locally in your web browser at: http://0.0.0.0:8002/data/postgresql
- Check against doc and design on all screen sizes 

## Issue / Card

Fixes # https://warthogs.atlassian.net/browse/WD-6433

2023-11-23 16:19 UTC, webteam-app commented
Demo starting at https://canonical-com-1124.demos.haus

2023-11-23 16:19 UTC, mtruj013 commented
Blocked pending missing links.

2023-11-27 17:50 UTC, carkod commented
@lyubomir-popov can you review?

2023-11-29 14:23 UTC, juanruitina commented
- [ ] Please put the Azure logo between AWS and Google Cloud as per the copy doc.
- [ ] PostgreSQL logo looks blurry on my screen (I know we've been having some issues with this lately, I think there's some kind of flag)
<img width="307" alt="Screenshot 2023-11-29 at 15 15 37" src="https://github.com/canonical/canonical.com/assets/1409729/d40e632b-3361-4dff-8ba7-e0d41f881778">

- [ ] The links in the resource section seem to lack some top margin/padding. Wrapping them in an `p` element seems to do the trick, but I don't know if that's the best practice.

<img width="647" alt="Screenshot 2023-11-29 at 15 21 10" src="https://github.com/canonical/canonical.com/assets/1409729/a3130d44-cb90-4cb7-b084-613bd9530c13">

Note: in the design all the logos are on a single row, maybe something to look at, having one or two "orphan" logos isn't great.

Feel free to change the label to UX+1 once you fix the first point, the other bits are visual anyway.

2023-11-29 14:59 UTC, mtruj013 commented
@juanruitina I reordered the logos that way as given of how many there are and how wide some of them are, there will always be at least 1 orphan. So there are basically 3 options here:

1. I order based on the doc without adding a break and have single orphan (the design feedback I've received in the past is that single orphans are not acceptable)
![Screenshot from 2023-11-29 15-55-27](https://github.com/canonical/canonical.com/assets/17607612/dba27527-4801-4897-8c50-0a843388fe5b)

2. I order based on the doc WITH a break and have weird spacing on the right most side of the first row:
![image](https://github.com/canonical/canonical.com/assets/17607612/2e2e172c-4ed5-43c0-b26e-f95ac1ec5f5c)

4. I keep it as is:
![image](https://github.com/canonical/canonical.com/assets/17607612/fdeeadcf-ded4-46c6-b672-dfd8a429f01d)


Let me know what you prefer and I'll make the necessary changes

2023-11-30 11:15 UTC, lyubomir-popov commented
Pushed a tiny fix, looks good, +1 @mtruj013

2023-11-30 16:45 UTC, lyubomir-popov commented
2 works best IMO

2023-12-01 11:44 UTC, lyubomir-popov commented
@mtruj013 for the logo section, version 2 please.

2023-12-01 11:48 UTC, mtruj013 commented
> for the logo section, version 2 please.

Already done :)

2023-12-01 13:14 UTC, aaryanporwal requested changes
Everything looks good :) Just one comment below.

2023-12-01 13:14 UTC, aaryanporwal commented on templates/data/postgresql.html
> +        </div>
Duplicate links

2023-12-01 13:28 UTC, aaryanporwal approved these changes
LGTM

2023-12-01 13:30 UTC, merged