WD-9529 - resize image on /data/opensearch
canonical/canonical.com pull request #1203
Opened 2024-03-12 13:27 UTC by lizzochek

## Done

Make logo on /data/opensearch larger

## QA

- [demo link](https://canonical-com-1199.demos.haus/documentation/open-documentation-academy)
- [linked issue](https://warthogs.atlassian.net/browse/DPNPM-415)
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the logo is larger

## Issue / Card
[WD-9529](https://warthogs.atlassian.net/browse/WD-9529)
Fixes #

## Screenshots

2024-03-12 13:27 UTC, webteam-app commented
Demo starting at https://canonical-com-1203.demos.haus

2024-03-12 22:49 UTC, lizzochek commented
@lorumic I confirmed it with @Sophie-32 Not sure whether it needs someone else to confirm

2024-03-13 04:31 UTC, akbarkz commented
@lizzochek I think it only needs the stakeholder's approval now. I sent her a link to demo instance, let's wait for her confirmation.

2024-03-13 07:44 UTC, akbarkz requested changes
Please make the size of the logo similar to one on MySQL data page. Also pls fix the size for Kafka and Spark pages accordingly.

2024-03-13 14:02 UTC, akbarkz approved these changes

2024-03-14 09:50 UTC, akbarkz commented
duplicate of https://github.com/canonical/canonical.com/pull/1205

2024-03-14 09:50 UTC, closed without merging