WD-10274 - update find a partner filters list
canonical/canonical.com pull request #1240
Opened 2024-04-18 09:58 UTC by lizzochek

## Done

Update find a partner filters list. Add ISV, IoT Devices and ODM to Programme section

## QA

- [demo link](https://canonical-com-1235.demos.haus/solutions/ai)
- [copy doc](https://docs.google.com/document/d/1R3s-aiSrFvbNrHjdfblYo_XX1f_EQ989DkmPS41seZc/edit)
- View the site on demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the page is updated correctly according to the copy doc

## Issue / Card
[WD-10274](https://warthogs.atlassian.net/browse/WD-10274)

2024-04-18 09:58 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://canonical-com-1240.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/18314)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-04-18 16:10 UTC, anthonydillon approved these changes
LGTM :+1:

2024-04-19 04:54 UTC, akbarkz commented
@lizzochek Please fix linting error

2024-04-19 08:23 UTC, akbarkz requested changes

2024-04-19 08:23 UTC, akbarkz commented on templates/partners/partial/_partner-filters/_programme-filters.html
> +  <span class="p-checkbox__label" id="iot-devices">IoT Devices</span>
Looks like this value is not working, must be something else, since there are no items shown when you select this option

2024-04-19 10:52 UTC, merged