WD-10729 - update contact form
canonical/canonical.com pull request #1270
Opened 2024-06-07 12:28 UTC by lizzochek

## Done

Updated contact form according to copy doc

## QA

- [demo link]()
- View the site on demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the forms are correct according to copy doc

## Issue / Card
[WD-10729](https://warthogs.atlassian.net/browse/WD-10729)

2024-06-07 12:28 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://canonical-com-1270.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/15785)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-07 13:49 UTC, lyubomir-popov commented
The page background is white, whereas checkbox backgrounds - paper. We should stick with one background colour. If this is on a rebranded page, then the paper colour would be the correct one.

2024-06-10 09:13 UTC, lyubomir-popov commented
I'd also move the asterisks at theend as they indent the text:
![image](https://github.com/canonical/canonical.com/assets/2741678/248407c0-fc48-4575-92cd-1abecf5c9c72)

2024-06-13 09:21 UTC, lyubomir-popov commented
Still not aligned with the underlying gid - the container should be 80 rem, with padding defined on 3 breakpoints, same asa with the `.row`:
![image](https://github.com/canonical/canonical.com/assets/2741678/99ca4fb2-a913-4984-ae68-21b34b54a6c3)

2024-06-14 10:53 UTC, lyubomir-popov commented
Fine above 1280px:
![image](https://github.com/canonical/canonical.com/assets/2741678/24325dcd-0199-4bb4-9210-9aa8cd62b851)

Still has some misalignments under that screen width: 
![image](https://github.com/canonical/canonical.com/assets/2741678/ec1b41d6-9b4d-473d-a808-b78360271c7b)
+1 lets fix the rest on the vanilla side
I've filed a vanilla enhancment issue here https://github.com/canonical/vanilla-framework/issues/5140

2024-06-14 11:57 UTC, akbarkz requested changes

2024-06-14 11:57 UTC, akbarkz commented on templates/partners/partial/_homepage-form.html
> +                       value="22.04 LTS" />
please add 24.04 LTS to the list of supported releases

2024-06-14 11:57 UTC, akbarkz commented on templates/partners/partial/_homepage-form.html
> +            <div class="col-4 u-sv3">
why are there two groups in the options?

2024-06-14 11:57 UTC, akbarkz commented on templates/partners/partial/_homepage-form.html
> +            <div class="col-4 u-sv3">
same here, why do you have two groups of options?

2024-06-14 11:57 UTC, akbarkz commented on templates/partners/partial/_homepage-form.html
> +            <div class="col-4 u-sv3">
here too

2024-06-14 11:59 UTC, akbarkz commented
@lizzochek Some of the fields did not go through, take a look at the screenshot (I filled all the fields, i.e. selected at least one checkbox in each):
![Screenshot 2024-06-14 at 16 57 38](https://github.com/canonical/canonical.com/assets/15943863/17b8a864-a3ec-4ca8-9a60-80143512c2d5)

2024-06-14 12:58 UTC, akbarkz commented
@lizzochek In the screenshot that I provided above take a look at a question "How do you consume open source?:". Its answer is a dot, even though it should be a value of checkboxes that I checked. Same is for the question about "Who is responsible for tracking..."

2024-06-14 13:23 UTC, akbarkz commented on static/js/modals.js
> +  const inputs = howManyMachinesFieldset?.querySelectorAll("input[name='how-many-machines-do-you-have']")
let's be consistent, we either put semicolon after each JS line or don't put them at all.

2024-06-14 13:23 UTC, akbarkz commented on static/sass/_pattern_forms.scss
> +  max-width: calc($grid-max-width + 2 * $spv--large - 2 * map-get($grid-margin-widths, default)) !important;
add indentation here

2024-06-14 13:23 UTC, akbarkz approved these changes

2024-06-14 13:39 UTC, merged