Dev created /solutions/ai/genai
canonical/canonical.com pull request #1402
Opened 2024-10-22 07:15 UTC by immortalcodes

## Done

Dev created /solutions/ai/genai

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check for all things related to addition of new page.
- [Design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions?node-id=873-6710&node-type=instance&m=dev)
- [Copydoc](https://docs.google.com/document/d/1eMvLlW6U-3ZWRRtY3Bq2u6EaFRqop4n6x8wgj3OWw-k/edit?tab=t.0)
- [Demo]()

## Issue / Card

Fixes # [WD-15327](https://warthogs.atlassian.net/browse/WD-15327)

## Screenshots

[if relevant, include a screenshot]

2024-10-22 07:15 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://canonical-com-1402.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/849)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-10-23 04:22 UTC, britneywwc reviewed
Looks good, just a couple minor things.

The dynamic form modal's country field doesn't have the dropdown selection
<img width="354" alt="Screenshot 2024-10-23 at 12 20 04 PM" src="https://github.com/user-attachments/assets/c63c3356-be96-405a-8099-2f9c5ca59584">

2024-10-23 04:22 UTC, britneywwc commented on templates/solutions/ai/genai.html
> +          <br class="u-hide--medium" />
The breakpoint doesn't match with design, should be after GenAI

2024-10-23 08:32 UTC, britneywwc approved these changes
Thanks for making the changes, beautiful work! 👯

2024-10-23 12:40 UTC, Sophie-32 commented
For navigation, this should follow the bubble navigation: https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0

2024-10-24 12:22 UTC, akbarkz requested changes

2024-10-24 12:22 UTC, akbarkz commented on secondary-navigation.yaml
> +    - title: AI
according to the copy doc this item should be for Edge AI

2024-10-24 12:43 UTC, akbarkz approved these changes

2024-10-24 12:44 UTC, merged