copy update: /data/opensearch/support
canonical/canonical.com pull request #1425
Opened 2024-11-13 22:28 UTC by jasmine-canonical

## Done
- Updates /data/opensearch/support to add "multiple packaging formats" section

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that /data/opensearch/support matches the [copy doc](https://docs.google.com/document/d/1ovtXv8RBybw-flvttyqWOzZivUryQMP34T1UGe90HlY/edit?usp=sharing)

## Issue / Card

Fixes [WD-16793](https://warthogs.atlassian.net/browse/WD-16793)

2024-11-13 22:28 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://canonical-com-1425.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/3461)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-11-14 16:10 UTC, Sophie-32 commented
Body text should be at the same level as the heading like the section below, see for reference - 
![Screen Shot 2024-11-14 at 5 09 58 PM](https://github.com/user-attachments/assets/5f4864c5-b6ac-4163-ae0f-cfd3cd06b84b)

2024-11-14 16:18 UTC, mtruj013 commented
@jasmine-canonical hey, thanks for your work on this! In the future could you please include the demo link with the relevant path in your pr description? This is documented as step 7 in the [copy update guide ](https://webteam.canonical.com/practices/copy-doc-updates). I've update the description to reflect how it should look. Thanks again and lmk if you have any questions :)

2024-11-14 17:04 UTC, jasmine-canonical commented
> Body text should be at the same level as the heading 

In the copy doc, it looks like the templates are different between the sections. This one is labelled as "TEMPLATE OPTIONS" whereas the one below is labelled "TEMPLATE BASIC TEXT". Should I still change it so that the body text is level with the heading?

2024-11-19 14:20 UTC, Sophie-32 commented
Aha! Thank you for pointing that out, the one labelled options is mislabbeled, that is also a basic text so should have theh same formatting. Thank you!

2024-11-20 13:48 UTC, mtruj013 requested changes
Thanks @jasmine-canonical, a couple comments in the code:

2024-11-20 13:48 UTC, mtruj013 commented on templates/data/opensearch/support.html
> +    </div>
I think it's best to use 50-50 split here. This makes the row responsive without needing to add additional col classes. Also, please wrap the row in the `p-section--shallow` instead, it's not recommended to mix grid and component classes like this

```suggestion
  <div class=p-section--shallow">
    <div class="row--50-50">
        <hr class="p-rule" />
        <div class="col">
          <h2>Multiple packaging formats</h2>
        </div>
        <div class="col">
          <p>
            We provide maintained and supported OpenSearch packages in both snap and container formats:
          </p>
        </div>
      </div>
  </div>
    
```

2024-11-20 13:48 UTC, mtruj013 commented on templates/data/opensearch/support.html
> +        <div class="row p-section--shallow">
Same here, these should be decoupled

2024-11-22 15:24 UTC, mtruj013 commented on templates/data/opensearch/support.html
> +        <div class="row p-section--shallow">
Sure thing, I meant that grid classes like `row` and components like `p-section--shallow` shouldn't be used on the same element (see discussion [here](https://chat.canonical.com/canonical/pl/yjjhnfdumtf5zm9ften6pghxeo)). It should be fixed on the lines you linked as well, good catch!

2024-11-29 15:29 UTC, mtruj013 approved these changes
Thanks @jasmine-canonical , LGTM!

2024-11-29 15:30 UTC, merged