Copy update: [WD-16878] Update /secure-open-source and Meganav
canonical/canonical.com pull request #1426
Opened 2024-11-14 13:30 UTC by Kxiru

## Done

- /solutions/secure-open-source (Now /solutions/open-source-security) according to copydoc.
- /solutions/ai/infrastructure edits to ensure consistency of links and terminology.
- Meganav edits according to copydoc

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes urgent copydoc issues.

## Screenshots

N/A

2024-11-14 13:30 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://canonical-com-1426.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/3519)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-11-15 04:21 UTC, akbarkz requested changes
Please add a redirect from the old URL to the new one, as specified in the description of the task.
Also, could you please add a link to the task, a copy doc and the page that needs QA to the description?
Thanks!

2024-11-15 04:21 UTC, akbarkz commented on templates/solutions/open-source-security/index.html
> +          <h5>Data Centers</h5>
```suggestion
          <h5>Data centers</h5>
```

2024-11-15 16:30 UTC, petesfrench approved these changes
LGTM

2024-11-15 16:30 UTC, petesfrench commented on templates/solutions/open-source-security/index.html
>              <li class="p-list__item is-ticked">Get fixes for critical vulnerabilities in under 24 hours on average</li>
```suggestion
            <li class="p-list__item is-ticked">Get fixes for critical vulnerabilities in 24 hours on average</li>
```

2024-11-15 16:36 UTC, petesfrench approved these changes

2024-11-15 16:38 UTC, merged