Page refresh: /solutions/ai
canonical/canonical.com pull request #1455
Opened 2024-12-09 15:48 UTC by goulinkh

## Done

- page refresh: AI solutions

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/solutions/ai
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Page redesign is applied properly

## Issue / Card

Fixes WD-17320

2024-12-09 15:48 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://canonical-com-1455.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/6341)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-12-10 14:53 UTC, eliman11 commented
Thanks @goulinkh, looks great! 

- [ ] The hero should look like the[ existing page](https://canonical.com/solutions/ai) with a 50/50 split and an embedded video on the right. We've amended the design on Figma - apologies for the confusion!
- [ ] Could you capitalize 'Ai infrastructure' to be 'AI infrastructure' under 'Use cases'
- [ ] Add missing 4th article under 'AI resources' section ([MicroK8s with Charmed Kubeflow on NVIDIA EGX platform](https://ubuntu.com/engage/microk8s-with-charmed-kubeflow-on-nvidia-egx)
Download the reference architecture for a detailed guide to infrastructure for machine learning use cases.)
- [ ] Could you add aria labels to logo cloud section please? I've added them to the [copydoc](https://docs.google.com/document/d/1AtAApqxX9cbWf4a3cakEYbk7OoTfdBBi7FlA3WZz5ZM/edit?tab=t.0#heading=h.3xyqigdoxmn5)
- [ ] Without changing styling, could we add h3 HTML tags to the subheadings under the images (i.e. Confidential AI, Data science, etc)
<img width="1453" alt="Screenshot 2024-12-10 at 14 37 19" src="https://github.com/user-attachments/assets/89f5485f-e44d-4cc5-86d1-b53827812695">

2024-12-10 17:23 UTC, mattea-turic commented
Thank you @goulinkh ! It looks great already :) Just a few small things from me:

- [ ] As @eliman11 already mentioned, I overlooked the fact that a video should belong in the hero, so could you change this to a 50/50 split and embed the video there pls?

For this section:
<img width="500" alt="Screenshot 2024-12-10 at 16 31 02" src="https://github.com/user-attachments/assets/a092e24d-4775-4a46-920a-baac5dee3dc7">

- [ ] I noticed the Intel logo isn't _quite_ aligned with the other logos, so I added an [updated asset](https://assets.ubuntu.com/v1/024a2182-intel-logo-updated-2.png), if you could replace the existing one

For this section:
<img width="500" alt="Screenshot 2024-12-10 at 16 35 00" src="https://github.com/user-attachments/assets/7fad6e71-2452-4e20-8098-497006fdc32f">
- [ ] Could you wrap the H2 in a shallow pls
- [ ] And also add a hr above the "fast-track compliance..." subsection?

For this section:
<img width="500" alt="Screenshot 2024-12-10 at 17 12 24" src="https://github.com/user-attachments/assets/f4ff8b39-a222-4f33-b9ca-c8f8b4d1c5e6">
- [ ] Could you use a link rather than a button, and add it in like so:
<img width="500" alt="Screenshot 2024-12-10 at 17 11 03" src="https://github.com/user-attachments/assets/2f57800c-ac93-45a9-9a47-27da3b0d7e67">

- [ ] And also there looks to be too much whitespace between the quotes, so could you make sure to wrap the first one in a shallow (I think it's a reg. one rn)


For this section:
<img width="500" alt="Screenshot 2024-12-10 at 17 16 35" src="https://github.com/user-attachments/assets/6a428804-5c30-4a72-b741-70f9741c22be">

- [ ] Could you add a hr above pls?

2024-12-11 11:28 UTC, goulinkh commented
Thanks for the review @mattea-turic and @eliman11 ! I've applied the requested changes, please let me know if they are matching what you expect and feel free to add further change requests if needed.

2024-12-11 15:17 UTC, eliman11 commented
Thanks @goulinkh for the changes! Looks good to me from UX for now - @mattea-turic probably mentioned already but we're waiting for external approval before going live so I'll keep the tag as UX needed for now in case anything changes.

2024-12-16 10:23 UTC, mattea-turic commented
Hi @goulinkh ! The PMs gave the go-ahead for deployment. The demo currently isn't working, but I'll give another quick review once it's up again. There were a couple of changes requested by them, but I'll flag this better once I can see how the page looks atm

2024-12-18 10:23 UTC, goulinkh commented
Hey @mattea-turic , I've restarted the demo link it should be working now. Let me know if this is looking good to go live.

2024-12-18 12:00 UTC, mattea-turic commented
Thanks @goulinkh , there are just a couple more things I wanted to add:

For the hero section:
- [ ] It looks like there's double wrapping going on, causing some extra whitespace at the bottom
- [ ] The line above the cta should be muted too pls

In the "use cases" section:
- [ ] Would it be possible to wrap each link in the first row in a shallow (for larger screens), so there's some more space between the first and second row? There might be a better way to do this, but that's at least what I did in the figma file. Actually, I notice now that the equal heights comp later on is less cramped – could this formatting be applied to the "use cases" section too?
- [ ] And if you could also apply H5 styling to the links
- [ ] Following conversation with PM and lead visual designer, I've swapped a couple of images: [AI infrastructure](https://assets.ubuntu.com/v1/6ccf256d-ai-infra.png), [Data management](https://assets.ubuntu.com/v1/cae6bdca-data-management.png), and [GenAI with RAG](https://assets.ubuntu.com/v1/7796e871-genai-rag.png)

For the "Designed for any silicon" section:
- [ ] Changes to copydoc were made, so that the logo section and link are no longer needed, and the text within the paragraph is a little different too ("including NVIDIA, Intel and AMD" removed)

For the "Run on any cloud" section:
- [ ] Another asset swap pls: [IBM](https://assets.ubuntu.com/v1/08c2f850-ibm-cloud-logo.png), [Oracle](https://assets.ubuntu.com/v1/c165433e-oracle-cloud-logo.png)
- [ ] Right above this section, where the full-width image is, could you remove the bottom padding from there so it reflects the figma file (again, this was a change made following more recent conversations)

For the CTA section at the bottom:
- [ ] The hr should be at the top of the section

Thanks for your patience with these changes!

2024-12-18 13:41 UTC, goulinkh commented
Hey @mattea-turic I've applied the suggested changes, let me know if you needed further updates.

2024-12-19 12:19 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/8c0cbace-8c20-43b1-b5f9-f944705dec70)
 [Design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/25.04-Canonical.com%2Fsolutions?node-id=1355-23906&m=dev) requires a shallow padding here

2024-12-19 12:20 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/65b3ca06-e9c6-4218-adc3-d3f2a6dc6b6a)

Similarly here

2024-12-19 12:21 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/4f2f385a-9e9f-41e1-927d-24a1b6a5b837)
![image](https://github.com/user-attachments/assets/a18738f2-18d2-418f-b60b-53415006cc17)

Missing Hrs here

2024-12-19 12:23 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/3e8e2729-5fc4-48c4-824a-810e9daf8252)
Confirming with @mattea-turic , I think we don't need shallow padding here (I don't see it in design)

2024-12-19 12:25 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/ab4af14a-8616-4c39-8a51-08e909e374c8)
Should be p-section--shallow for this

2024-12-19 12:27 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/dd99b059-ed66-4028-9d03-1f5a72561a2d)
There is way more space here, It might be helpful to turn on dev mode in design and it will help you know what padding to choose, button is here
![image](https://github.com/user-attachments/assets/07e430a7-b9fe-477a-8977-34e638862ffd)

2024-12-19 12:30 UTC, immortalcodes commented
![image](https://github.com/user-attachments/assets/75309779-2b61-4793-b1d5-451c3388c930)
Too much space appears on smaller screen in this section, could you please take care of it

2024-12-19 12:52 UTC, immortalcodes requested changes
Thanks for your work. I have left some comments, please feel free to apply changes at all places applicable

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
>             aria-controls="ai-modal">Contact Canonical</a>
I think we can repalce this section with hero_macro https://vanillaframework.io/docs/patterns/hero

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
>        <div class="col">
```
    <h2>
          Why Canonical
          <br class="u-hide--small" />
          for enterprise AI?
        </h2>
```
Hiding it on small screen will make it better

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
> +        <a href="https://pages.ubuntu.com/rs/066-EOV-335/images/Datasheet%20for%20MLOps%20workshop.pdf?version=0">Download the AI workshop datasheet&nbsp;&rsaquo;</a>
Please use `p-cta-block` here and at other places that have a call to action.
Refer here https://vanillaframework.io/docs/patterns/cta-block

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
> +                loading="auto",
Images that are instantly visible on the top of page should be `auto` loaded and the images at the bottom of pages can be `lazy` loaded.

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
> -                height="66",
CTA-block here please

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
> +  </div>
```suggestion
    <hr class="p-rule is-fixed-width" />
```

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
>        <hr class="p-rule" />
Vanilla suggests that `u-fixed-width`/`row` should not be in same div as `p-section .*`
Could you please refractor it, by that I mean to create 2 divs above one another and put these classes in different divs.
Could you also please do this for rest of code.
Thanks

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
> +        <div class="row p-section--shallow">
similar to above comment

2024-12-19 12:52 UTC, immortalcodes commented on templates/solutions/ai/index.html
> +        <div class="col-3 col-medium-2">
```suggestion
      <div class="row">
            <hr class="p-rule--highlight" />
        <div class="col-3 col-medium-2">
```

2025-01-07 10:26 UTC, goulinkh commented
> ![image](https://private-user-images.githubusercontent.com/92226302/397374112-3e8e2729-5fc4-48c4-824a-810e9daf8252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNDQwOTEsIm5iZiI6MTczNjI0Mzc5MSwicGF0aCI6Ii85MjIyNjMwMi8zOTczNzQxMTItM2U4ZTI3MjktNWZjNC00OGM0LTgyNGEtODEwZTlkYWY4MjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDA5NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzAwOTRiMzM2YmUwMGQyNGE3OWI3Y2Q1NzVjOGQ5NzJiNjcxNjg3YzBhMzJhZDBlYjFlMDg3MWRlNTA4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qSdwzwAkOT64bUCVTf-yuY0916E3U-RU0OQT6251WBA) Confirming with @mattea-turic , I think we don't need shallow padding here (I don't see it in design)

Removing the shallow attributes makes the UI too long and not be aligned with the design anymore.
Could you please confirm that shallow is unnecessary @mattea-turic ?

Screenshot of this section without the shallow attribute:
![image](https://github.com/user-attachments/assets/be9a8326-e6f6-4c14-85bd-b3724bbc2c91)

2025-01-07 10:56 UTC, goulinkh commented
Thanks for the review @immortalcodes and the Figma tips! Can you take a look at this again.

2025-01-07 12:34 UTC, mattea-turic commented
@goulinkh 
> 
> Removing the shallow attributes makes the UI too long and not be aligned with the design anymore. Could you please confirm that shallow is unnecessary @mattea-turic ?
> 

I'm not sure that I fully understand what you mean here, but I'd say it looks good as is on the current demo. In the screenshot you provided, there looks to be too much whitespace imo, but you mention this is without the shallow? 

And just a heads-up, I think a bunch of hrs have gotten duplicated e.g. 
<img width="500" alt="Screenshot 2025-01-07 at 12 33 13" src="https://github.com/user-attachments/assets/a3fd6089-835b-434a-a736-0edb54b843f5" />

2025-01-08 11:39 UTC, immortalcodes commented
> > ![image](https://private-user-images.githubusercontent.com/92226302/397374112-3e8e2729-5fc4-48c4-824a-810e9daf8252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNDQwOTEsIm5iZiI6MTczNjI0Mzc5MSwicGF0aCI6Ii85MjIyNjMwMi8zOTczNzQxMTItM2U4ZTI3MjktNWZjNC00OGM0LTgyNGEtODEwZTlkYWY4MjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDA5NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzAwOTRiMzM2YmUwMGQyNGE3OWI3Y2Q1NzVjOGQ5NzJiNjcxNjg3YzBhMzJhZDBlYjFlMDg3MWRlNTA4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qSdwzwAkOT64bUCVTf-yuY0916E3U-RU0OQT6251WBA) Confirming with @mattea-turic , I think we don't need shallow padding here (I don't see it in design)
> 
> Removing the shallow attributes makes the UI too long and not be aligned with the design anymore. Could you please confirm that shallow is unnecessary @mattea-turic ?
> 
> Screenshot of this section without the shallow attribute: ![image](https://private-user-images.githubusercontent.com/36013798/400729921-be9a8326-e6f6-4c14-85bd-b3724bbc2c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMzY0MzgsIm5iZiI6MTczNjMzNjEzOCwicGF0aCI6Ii8zNjAxMzc5OC80MDA3Mjk5MjEtYmU5YTgzMjYtZTZmNi00YzE0LTg1YmQtYjM3MjRiYmMyYzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDExMzUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYmJhY2Y2OWI3NjZiZTMxYTIwOTg3Yzk1Yzg0YWYzZjAzZjE1NzE5YjRmZDFhNjQ5MTY4ZWM1Mjk4MDBlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Xpj0_-n-XAkDkiUKhRjEkdcbooJGrzI9LcIJEgdvhmc)

Oh I meant no shallow padding at all, removing the shallow attribute will add regular padding but if @mattea-turic feels it is good I am fine

2025-01-08 12:43 UTC, immortalcodes requested changes

2025-01-09 11:26 UTC, immortalcodes approved these changes
Minor changes and it should be good to go.
Thanks

2025-01-09 11:26 UTC, immortalcodes commented on templates/solutions/ai/index.html
> +        <h2>All the open source you need for AI</h2>
```suggestion
    <div class="p-section--shallow">
      <div class="row">
      <hr class="p-rule" />
        <h2>All the open source you need for AI</h2>
```

2025-01-09 17:45 UTC, merged