Build withdrawal modal
canonical/canonical.com pull request #595
Opened 2022-07-27 10:38 UTC by minkyngkm

## Done

Build withdrawal modal

## QA

- Go to /careers/application/token (Please ping me for token)
- Click application withdrawal button and check modal pops up

## Issue / Card

Fixes #583 

## Screenshots

![image](https://user-images.githubusercontent.com/57550290/181227277-7d937ca7-0272-4bfc-be0c-ab4f82d65ad4.png)

2022-07-27 10:38 UTC, webteam-app commented
Demo starting at https://canonical-com-595.demos.haus

2022-08-02 12:57 UTC, anthonydillon requested changes
Few suggestions in the code @minkyngkm

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +        <p>Your hiring lead is {{ hiring_lead["name"] }} (<a href="mailto:{{ hiring_lead['primary_email_address'] }}">{{ hiring_lead["primary_email_address"] }}</a>)</p>
I thought we were not putting the HL email here? @marinacastejon

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +      <h2>Your application proces</h2>
```suggestion
      <h2>Your application process</h2>
```

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +              There are three parts to this stage:
```suggestion
              <p>There are three parts to this stage:</p>
```

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +            <h4 class='u-no-margin--bottom'>
I don't think we should remove the typographic rhythm throughout this page.

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +              {% else %}<i class="p-icon--information"></i>
Can you please add a11y text within the icon. This will be hidden from the screen but will be read by a screen reader.

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +      <i class="p-icon--success"></i> You are hired! Welcome to Canonical.
```suggestion
      <i class="p-icon--success">Success:</i> Your application has been successful. Welcome to Canonical!
```

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/withdrawal.html
> +    <p>Thank you for the time you have spent on this application. <br/> If you wish to know more about other</p>
This sentence is incomplete

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/withdrawal.html
> +    <h1>Your application has been withdrawn.</h1>
No use of grid?

2022-08-02 12:57 UTC, anthonydillon commented on templates/applications/application.html
> +    <h1>Thanks for applying {{ candidate["first_name"] }} {{ candidate["last_name"] }}!</h1>
No grid use?

2022-08-02 12:59 UTC, anthonydillon commented on templates/applications/withdrawal.html
> +    <h1>Your application has been withdrawn.</h1>
```suggestion
    <h1>Your application has been withdrawn</h1>
```

2022-08-02 12:59 UTC, anthonydillon commented on templates/applications/withdrawal.html
> +    <p>Thank you for the time you have spent on this application. <br/> If you wish to know more about other</p>
There is no information about a follow up email confirmation?

2022-08-05 06:44 UTC, minkyngkm commented
Closing this PR as the other PR includes everything in this PR. All the suggestions/comments will be addressed in the other PRs (#602, #593)

2022-08-05 06:44 UTC, closed without merging