Update navigation to new vanilla pattern & new items WIP
canonical/canonical.com pull request #650
Opened 2022-10-11 13:30 UTC by petesfrench

## Done

Update navigation to new vanilla pattern & new items based on the items listed in [the issue](https://github.com/canonical/web-squad/issues/6054) and [the wireframe](https://miro.com/app/board/o9J_luilNcw=/?moveToWidget=3458764526315426035&cot=14)

## QA

- Check the design matches the [new vanilla pattern](https://vanillaframework.io/docs/patterns/navigation)
- Check all the items listed in [the issue](https://github.com/canonical/web-squad/issues/6054) are present

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/6054

2022-10-11 13:30 UTC, webteam-app commented
Demo starting at https://canonical-com-650.demos.haus

2022-10-11 15:08 UTC, spencerbygraves commented
@petesfrench I think you could extend the hover of indented items to full width, and keep the text the same style as the level above. Thanks.

2022-10-11 16:35 UTC, petesfrench commented
Thanks @spencerbygraves , could you take another look please

2022-10-12 08:48 UTC, carkod commented
@petesfrench are you merging into the wrong branch, should be main?

2022-10-13 10:30 UTC, petesfrench commented
@carkod It was requested alongside work on the application page that is already on main. @marinacastejon Do you know if this is supposed to go to production?

2022-10-13 10:52 UTC, carkod commented
> @carkod It was requested alongside work on the application page that is already on main. @marinacastejon Do you know if this is supposed to go to production?

Sorry, I meant "it shouldn't be main"? Because the about us page is going 404. We probably don't want this to happen in prod, right?

2022-10-13 11:05 UTC, spencerbygraves commented
Thanks @petesfrench, I think that looks better.

2022-10-14 10:35 UTC, sowasred2012 requested changes
A lot of the broken links exist currently on the site:
Company:
- About: drop this one, there is nothing we can use at the moment
- Blog: /blog
- Documentation:
- Press centre: /press-centre

Partners:
- About: drop for now
- Our partner programmes: /partners
- Channel/reseller: /partners/channel-and-reseller
- IoT: /partners/iot-device
- Log in to the partner portal: https://partner-portal.canonical.com/
- Also, a number of these pages have a white strip above the main suru that can be gotten rid of:
 ![image](https://user-images.githubusercontent.com/2376968/195826524-8a72afd7-fa86-47d6-bc9b-0bd223b2efea.png)

Careers:
- Overview: /careers
- Open Roles: /careers/all
- Career finder: /careers/start (this is 500ing on the demo, not sure why)
- Working at Canonical: the closest we currently have is /careers/departments

2022-10-14 10:43 UTC, sowasred2012 commented on static/sass/styles.scss
> +ul.p-navigation__dropdown-sub-list {
@petesfrench I think it's worth opening an issue for this in Vanilla, I'm surprised it doesn't already have something for this use case (or maybe it does, but it's hidden away and needs to be documented).

2022-10-14 10:49 UTC, sowasred2012 commented on templates/partial/_navigation.html
> +              <a href="/company/blogs" class="p-navigation__dropdown-item">Blogs</a>
```suggestion
              <a href="/company/blogs" class="p-navigation__dropdown-item">Blog</a>
```

2022-10-14 10:54 UTC, sowasred2012 commented on templates/partial/_navigation.html
> +        <li class="p-navigation__item--dropdown-toggle" id="company">
@spencerbygraves @lyubomir-popov @al-bakalova - can we get some advice on this please - if a navigation item is within a dropdown menu, how do we indicate the currently active nav item to the user?

![Peek 2022-10-14 11-48](https://user-images.githubusercontent.com/2376968/195829682-7c4c5c3a-ece5-4e98-b9de-fb529ea05a5a.gif)

My thought is to add `.is-selected` to the dropdown toggle, and then an active state to the links (which I'm not sure exists in Vanilla). What do you think?

2022-10-14 10:54 UTC, sowasred2012 commented on templates/partial/_navigation.html
> +        <li class="p-navigation__item--dropdown-toggle" id="company">
Demo here: https://canonical-com-650.demos.haus/

2022-10-17 10:02 UTC, lyubomir-popov commented
@sowasred2012 my proposal: 
![image](https://user-images.githubusercontent.com/2741678/196149851-44c146fe-f90a-455b-a779-ce063d821027.png)

2022-10-18 14:46 UTC, petesfrench commented
@lyubomir-popov I have tried to replicate what you provided as best I could, can you take a look and give me some feedback please

2022-10-25 10:19 UTC, sowasred2012 reviewed
Looking good! The only thing remaining is that the "Products" item in the nav doesn't scroll to the Products section for some reason

2022-10-25 13:30 UTC, sowasred2012 approved these changes
Nice! :rocket:

2022-10-26 10:37 UTC, merged