Update department pages and add latest news
canonical/canonical.com pull request #701
Opened 2022-11-28 10:07 UTC by mtruj013

## Done

- Updated department pages and added latest news module

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-536

2022-11-28 10:07 UTC, webteam-app commented
Demo starting at https://canonical-com-701.demos.haus

2022-12-05 14:58 UTC, lyubomir-popov commented
@marinacastejon @mtruj013 Can we do something like this for the featured roles?

![image](https://user-images.githubusercontent.com/2741678/205668266-8db8e65a-011a-4be6-8f4b-dccdb586a855.png)

- rows with `gap: 0`
- cards with padding .5rem 1rem 1rem 1rem;`
- hrs with no `margin-bottom`
- card hover/active states using  these vanilla varialbes for background opacity (color rgba(0,0,0, {insert var here})): 
- 
```
$input-background-opacity-amount: 0.04;
$hover-background-opacity-amount: 0.05;
```

2022-12-09 11:07 UTC, marinacastejon commented
Hi @mtruj013 there are a few things to be updated, but you might want to wait for @lyubomir-popov to update the mock-ups. 
- Title "Fast track jobs" should be updated as described in this [JIRA issue](https://warthogs.atlassian.net/browse/WD-535). Lyubo was briefed. 
- From what I see in the mock-ups from visual the photo is not in the right place, it should be in the middle of the content, not just after the heading.  
- In the section with the social media links, the pages where github shows should only show Github's logo, not the branches and the stars. This is an error from the mock-ups, I have tagged Lyubo in figma to fix it. 

Thanks!

2022-12-09 16:22 UTC, sowasred2012 commented on static/sass/styles.scss
> +    padding: 0 1rem 1rem;
should be alphabetical order

2022-12-09 16:27 UTC, sowasred2012 reviewed
A point for design, but it really wasn't clear to me what the link was on these blog sections - I thought it'd be the image initially, then I went looking for a "Read more" esque link, then realised it's the heading: 
![image](https://user-images.githubusercontent.com/2376968/206747053-d0c9e107-bde4-453a-93ad-157e557c0a85.png)

Also, I don't think we should show the "[...]", it looks messy. Is there a short summary we could pull in instead?

2022-12-09 16:29 UTC, sowasred2012 commented on static/sass/styles.scss
> +    // @include vf-transition(#{background-color, border-color}, snap, in);
commented out code

2022-12-09 16:41 UTC, anthonydillon approved these changes
QA looks good to me :+1:

2022-12-09 16:44 UTC, sowasred2012 requested changes
Looking good overall, but a few comments in the code - I also think there's some possibilities to move things into partials to cut down the amount of repeated code, or code where the only difference is something minor, like copy or an ID, i.e. the header and footer - these pages will be monsters to update later otherwise. Happy to pair on it.

2022-12-09 16:44 UTC, sowasred2012 commented on templates/careers/administration.html
> +        height="834",
This image can't physically be wider than 1242px, so I think setting these dimensions will reduce the file size when pulling it from cloudinary:
```suggestion
        width="1242",
        height="467",
```

2022-12-09 17:03 UTC, lyubomir-popov commented
@sowasred2012 good point, can we make the blog titles blue?

2022-12-12 09:37 UTC, sowasred2012 commented
@Zoospora could you give this a design review pls?

2022-12-13 10:10 UTC, Zoospora commented
Some comments regarding the featured positions: 
It would be great if we could adjust a little more to lyubo's proposal (a few messages above). I attach again the image, although in the message there are more precise indications about its implementation.

![example](https://user-images.githubusercontent.com/9861718/207289410-76c015c1-c753-4fbc-99c0-d79baefc062a.png)

I would swear that according to Vanilla the last rows in a table do not usually have a bottom line. 
It would be ideal if the height is consistent so that the sections don't look so close together. 
Even if there is only one element in a second row, I think it would be ideal if the top line went all the way to the end. I am attaching some screenshots of the details mentioned:

![finance](https://user-images.githubusercontent.com/9861718/207289466-ca6f8856-be58-4ba0-951a-1
![marketing](https://user-images.githubusercontent.com/9861718/207289473-1ab7318c-4499-455d-97dd-fa617dc08923.png)
772646a999d.png)
![operations](https://user-images.githubusercontent.com/9861718/207289482-91e221ea-9b98-4b3e-9667-8db59
![people](https://user-images.githubusercontent.com/9861718/207289489-56bcc6bf-86ec-47b1-885d-cc26e61e080e.png)
16880bb.png)
![webanddesign](https://user-images.githubusercontent.com/9861718/207289502-317ddee6-6e14-4b14-9e33-e0a06d58ba1b.png)

Thanks!

2022-12-14 09:22 UTC, marinacastejon commented
Hi @mtruj013 , 
The [sales page](https://canonical-com-701.demos.haus/careers/sales) doesn't load the blog images for me. 
Other than that, looks good to me, thanks for implementing the changes I mentioned.

2022-12-14 11:28 UTC, petesfrench commented
This button at the bottom of the /careers page take you to /careers (ie. back to the top of the same page). Is this the intended behaviour?
![image](https://user-images.githubusercontent.com/58276363/207583693-1753d535-7493-4acd-9175-9b5a11cc97f7.png)

2022-12-14 15:54 UTC, petesfrench commented
Hey @Zoospora, I have made those changes could you take another look please? I wasn't completely sure what you meant by the same height, so I have given each job posting a fixed height.

2022-12-14 17:43 UTC, lyubomir-popov commented
> Hey @Zoospora, I have made those changes could you take another look please? I wasn't completely sure what you meant by the same height, so I have given each job posting a fixed height.

I've adjusted them as they should be, not sure fixed hieght is a good idea - sooner or later something will overflow. The height should be the text's height plus a set margin-bottom.

2022-12-14 17:44 UTC, lyubomir-popov commented
@petesfrench aontehr thing I noticed - all headings should be `p-heading--2`. There's a few places where there are h3s, h1s, etc: 
![image](https://user-images.githubusercontent.com/2741678/207668669-fb288c99-7e26-45ff-a011-5559b52d6db4.png)

2022-12-15 06:50 UTC, Zoospora commented
> > Hey @Zoospora, I have made those changes could you take another look please? I wasn't completely sure what you meant by the same height, so I have given each job posting a fixed height.
> 
> I've adjusted them as they should be, not sure fixed hieght is a good idea - sooner or later something will overflow. The height should be the text's height plus a set margin-bottom.

perfect, thanks!!

2022-12-15 09:56 UTC, petesfrench commented
@lyubomir-popov I have applied the changes from sales onto the rest of the pages and updated the remaining h3's to be p-heading--2. I have updated the scss to not be a fixed height, can you take a look please

2022-12-15 11:31 UTC, Zoospora commented
Hey, thanks for the changes! I just see one thing that doesn't quite add up for me. I think the hover should go all the way to the divider line itself and not leave that little margin in between. I'm sorry if I missed any explanation at some point. Thanks in advice!

![hover](https://user-images.githubusercontent.com/9861718/207848692-34073d22-6696-4caa-8dd3-b52956841ae5.png)

2022-12-15 12:41 UTC, mtruj013 commented
> This button at the bottom of the /careers page take you to /careers (ie. back to the top of the same page). Is this the intended behaviour? @marinacastejon ![image](https://user-images.githubusercontent.com/58276363/207583693-1753d535-7493-4acd-9175-9b5a11cc97f7.png)

Hey @petesfrench, thanks for helping with this! Just to add some context, this routes back to the same page because /careers/departments has been deleted and there's a redirect in place that routes the user back to this page if they try to visit the old departments overview. There is a dependant [PR](https://github.com/canonical/canonical.com/pull/720) that deletes this section altogether though. I separated the work for the careers landing page so as to not add to this already massive pr, with the idea that it would be merged directly after this one

2022-12-15 15:14 UTC, merged