Split role description and application page
canonical/canonical.com pull request #759
Opened 2023-01-20 08:14 UTC by mtruj013

## Done

- Separated application form and job description 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/all
- Click on any job posting on and see that you only see the job description
- Scroll down and click "Apply" and see that you are taken to the form and that the url now has the `/application` in the path
- At the top of the page click "Back to role description" and see that the form is once again hidden and the url does not have `/aplication` in the path 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-958

2023-01-20 08:14 UTC, webteam-app commented
Demo starting at https://canonical-com-759.demos.haus

2023-01-20 10:03 UTC, lyubomir-popov commented
@mtruj013 can we please do this on both the text and form page?
![image](https://user-images.githubusercontent.com/2741678/213668499-1d17ac69-dfde-414c-b7c6-774286ae7ab6.png)

- add `p-heading--2` to h1
- - add `p-heading--5` to the h4s
- split layout on desktop, as is one smaller screens

2023-01-20 10:34 UTC, anthonydillon requested changes
A few suggestions in the code

2023-01-20 10:34 UTC, anthonydillon commented on templates/careers/job-detail.html
> +    <p><a class="p-button--positive" id="apply-button">Apply</a></p>
This is invalid mark up. Links need to have a `href` attribute

2023-01-20 10:34 UTC, anthonydillon commented on templates/careers/base_job-details.html
> +<section class="p-strip u-extra-space u-hide" id="application">
I don't think we need the `u-extra-space` class anymore.

2023-01-20 10:34 UTC, anthonydillon commented on templates/careers/base_job-details.html
> +<section class="p-strip u-extra-space" id="details">
I don't think we need the `u-extra-space` class anymore.

2023-01-20 10:34 UTC, anthonydillon commented on templates/careers/base_job-details.html
> +  application_form = document.getElementById("application")
Missing `const`

2023-01-20 10:34 UTC, anthonydillon commented on templates/careers/base_job-details.html
> +    window.history.replaceState({}, document.title, `${window.location.pathname}/application`);
```suggestion
    window.history.replaceState({}, document.title, `${origin_url}/application`);
```

2023-01-20 10:34 UTC, anthonydillon commented on templates/careers/base_job-details.html
> +  function show_application(){
Could you also add a scrollTo(application_form) so the user is in the right place?

2023-01-23 10:05 UTC, marinacastejon commented
Hi @mtruj013 thanks for this. LGTM, except for a small detail. When I go back in the browser from the application form page, it takes me to the open roles page, instead of the previous page which is the job description page. Is it feasible to change the behaviour so that I'm directed to the job description page? Thanks

2023-01-23 13:45 UTC, mtruj013 commented
@anthonydillon @marinacastejon @lyubomir-popov hi all, thanks for the feedback! I've addressed your comments if you all could take another look?

2023-01-23 19:26 UTC, anthonydillon approved these changes
LGTM :+1:

2023-01-23 19:26 UTC, anthonydillon commented on static/sass/styles.scss
> +    @extend %vf-heading-5;
Nice 👍

2023-01-25 08:16 UTC, marinacastejon commented
@mtruj013 Thanks for this, LGTM 👍

2023-01-26 09:42 UTC, mtruj013 commented
@lyubomir-popov

2023-01-26 09:58 UTC, merged