Include departments with no vacancies
canonical/canonical.com pull request #779
Opened 2023-02-03 15:16 UTC by mtruj013

## Done

- Fixed missing departments
- Fixed 404ing career-explorer

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- See that Administration and Legal show up in overview and take you to the correct dept page
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/career-explorer
- See that the page renders successfully 

## Issue / Card

Fixes # https://warthogs.atlassian.net/browse/WD-1734

2023-02-03 15:16 UTC, webteam-app commented
Demo starting at https://canonical-com-779.demos.haus

2023-02-03 16:11 UTC, anthonydillon requested changes
When clicking through the button to "See all Administration roles" does not show no roles.

2023-02-03 16:11 UTC, anthonydillon commented on webapp/app.py
> +@app.route("/careers/career-explorer")
There are links to the old page on the homepage and navigation which leads to a 404. Can you add a redirect and update links across this project.

2023-02-03 17:08 UTC, mtruj013 commented
Thanks @anthonydillon! I've addressed your comments if you'd like to take another look?

2023-02-03 18:35 UTC, anthonydillon approved these changes
LGTM thanks @mtruj013 👍

2023-02-06 09:32 UTC, marinacastejon commented
LGTM, thanks @mtruj013

2023-02-06 10:46 UTC, mtruj013 commented
Regarding the changed CTAs: It decided via MM that they should be changed to "Show all roles" as these departments do not currently have open roles

2023-02-06 13:10 UTC, merged