WIP Build culture page
canonical/canonical.com pull request #832
Opened 2023-04-06 09:48 UTC by carkod

## Done

[List of work items including drive-bys]

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

2023-04-06 09:48 UTC, webteam-app commented
Demo starting at https://canonical-com-832.demos.haus

2023-04-07 09:14 UTC, anthonydillon requested changes
Thanks @carkod this page is looking good. Few suggestions in the code.

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +{% block meta_description %}Canonical prefers internal promotion and encourages high-performing colleagues to pursue diverse roles at the company over the course of their career, to develop a well-ro
This is not the description for this page

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +{% block meta_copydoc %}https://docs.google.com/document/d/1PAeP_ZO4JzSBCi-fRp6F7SYtSSRY-4DcWLUf9HJaMxs/edit#heading=h.yys3mdcj4xua{% endblock meta_copydoc %}
Can you remove the heading hash

2023-04-07 09:14 UTC, anthonydillon commented on static/sass/styles.scss
> +  margin-top: 0.5625rem;
Your still using online styling in the page

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +        <div class="col-3 col-medium-1" style="margin-top: 0.5625rem">
I would suggest trying to get the profile images and quotes side by side in small screens.

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +        <p>We aspire to lead on the global stage. Most of us are avid students of greatness - we are interested in how the latest technologies work, how the best organisations work and how the smarte
Can you encode the dash here please?

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +        <p>We aspire to lead on the global stage. Most of us are avid students of greatness - we are interested in how the latest technologies work, how the best organisations work and how the smarte
I would suggest "documentation practise" should be the text of the link.

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +          <h4 class="p-heading--2 u-data-border--top"><strong>950+</strong><br>Employees</h3>
Starting h4, closing h3

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +          <h4 class="p-heading--2 u-data-border--top"><strong>89</strong><br>Countries</h3>
Starting h4, closing h3

2023-04-07 09:14 UTC, anthonydillon commented on templates/careers/company-culture.html
> +          <h4 class="p-heading--2 u-data-border--top"><strong>78</strong><br>Languages</h3>
Starting h4, closing h3

2023-04-12 08:48 UTC, carkod commented
> @carlos looks great! A couple of small glitches:
> 
> * space under image making text misaligned:
> 

@lyubomir-popov Can I get another review? Thanks

2023-04-12 08:59 UTC, lyubomir-popov commented
@carkod the grid nesting is a bit wrong:
![image](https://user-images.githubusercontent.com/2741678/231406123-c58c76cb-3612-444e-b089-5f5e0fd6660a.png)
that happens because you put stuff inside a row that is not a child of col-* - so the grid implicitly creates columns for those things. your markup should lookc like this:
![image](https://user-images.githubusercontent.com/2741678/231407285-997e016d-522e-424e-b398-cdce1814d559.png)
and not like this (current): 
![image](https://user-images.githubusercontent.com/2741678/231407340-7482d404-d0d2-43bb-97e5-19679e1a9be7.png)
to add more stuff, you ca nwrap it in a col-9 or ad another row inside

2023-04-12 09:00 UTC, lyubomir-popov commented
Adding plus one so you don't have to request another review but please fix the grid as described above

2023-04-12 14:40 UTC, marinacastejon commented
Hi @carkod as discussed in MM, can you please change the "Remote" link so that it says "Travel and Lifestyle" in the meantime? Otherwise people click on sth that says Remote work and end up in a page that has a different name. I've created a task in JIRA to update it later on with a dependency on the updated remote work page

2023-04-12 16:51 UTC, carkod commented
> @carkod the grid nesting is a bit wrong: ![image](https://user-images.githubusercontent.com/2741678/231406123-c58c76cb-3612-444e-b089-5f5e0fd6660a.png) that happens because you put stuff inside a row that is not a child of col-* - so the grid implicitly creates columns for those things. your markup should lookc like this: ...

Got it. Done.

2023-04-13 08:43 UTC, carkod commented
> Hi @carkod as discussed in MM, can you please change the "Remote" link so that it says "Travel and Lifestyle" in the meantime? Otherwise people click on sth that says Remote work and end up in a page that has a different name. I've created a task in JIRA to update it later on with a dependency on the updated remote work page

@marinacastejon can you take another look?

2023-04-13 08:56 UTC, marinacastejon commented
Hi @carkod Thanks! I found a small thing, the link Explore careers, redirects to /careers, but it should go to the career explorer page. Let me know when you're done and I'll +1 this.

2023-04-14 07:04 UTC, marinacastejon commented
👍 LGTM, thanks @carkod

2023-04-14 08:25 UTC, merged