Update /become-a-partner
canonical/canonical.com pull request #887
Opened 2023-06-12 14:40 UTC by ClementChaumel

## Done

- Updated the [/become-a-partner](https://canonical-com-887.demos.haus/partners/become-a-partner) page according to [the design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9427-18076&t=2gCmy0Ck7MrzwKzA-0)
- Removed outdated `is-paper` class
- Formatted `styles.scss`

## QA

- Compare [/become-a-partner](https://canonical-com-887.demos.haus/partners/become-a-partner) against [the design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9427-18076&t=2gCmy0Ck7MrzwKzA-0)
- Make sure that it looks correct and nothing is broken

## Issue / Card

Fixes WD-3745

## Before merging
If the image is the final one we want to use we should add it to the asset manager instead of hotlinking.

2023-06-12 14:40 UTC, webteam-app commented
Demo starting at https://canonical-com-887.demos.haus

2023-06-13 09:32 UTC, lyubomir-popov requested changes
A couiple of comments in figma https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9960%3A24523&t=iDY29WLvf5WCb1hc-1

2023-06-13 09:32 UTC, lyubomir-popov commented on static/sass/styles.scss
> +  grid-template-rows: 477px 106px 1fr;
This feels very fragile, and won't update when the value of 1rem changes after 1680px. Can this be done with just a regular strip wrapping this and then using the variable in the regular strip for an overlap value?

2023-06-13 14:36 UTC, mtruj013 approved these changes
LGTM, just a couple super minor comments. Also not sure if the split is supposed to be 50/50 on medium screens like we've been doing for new pages on u.com, @lyubomir-popov could you confirm?

2023-06-13 14:36 UTC, mtruj013 commented on templates/partners/become-a-partner.html
> +      <p>By formalising their partnership with Canonical, technology companies of all kinds –
```suggestion
      <p>By formalising their partnership with Canonical, technology companies of all kinds &ndash; 
```

2023-06-13 14:36 UTC, mtruj013 commented on templates/partners/become-a-partner.html
> +from hardware makers and ISVs to cloud providers and systems integrators – benefit from significant opportunities to increase their revenues with Ubuntu.
```suggestion
from hardware makers and ISVs to cloud providers and systems integrators &ndash; benefit from significant opportunities to increase their revenues with Ubuntu.
```

2023-06-14 11:37 UTC, lyubomir-popov approved these changes
I pushed the changes I'd like to see, so giving a +1.
@ClementChaumel please have a look at what I've done code-wise:, the grid refactor, the overlap calculations in particular.


![image](https://github.com/canonical/canonical.com/assets/2741678/6449bb81-f7de-4055-ab07-6d3733c0eefe)
![image](https://github.com/canonical/canonical.com/assets/2741678/9f20c8c1-b85a-4e62-8c47-37f2889f8a9a)

2023-06-14 15:29 UTC, lyubomir-popov commented
> layout? And maybe name it + explain in which cases it should be used?
> And generally, could you expand on how each layout's (50%-50%, 25%-75%, etc) responsiveness?

Yes we discussed this with @bartaz today in the standup. We'll have a short session to describe the variants we need tomorrow and we'll document the decisions.

2023-06-15 11:04 UTC, merged