Documentation practice
canonical/canonical.com pull request #907
Opened 2023-06-23 21:35 UTC by lyubomir-popov

## Done

Based on @mtruj013's [pr](https://github.com/canonical/canonical.com/pull/905). I changed a few things so pushing to a separate pr so as to not break anything.

This is a bit different from the design, as I talked to Daniele since we did the pages and he expressed a preference for a denser treatment on documentation pages, and liked placing headings on the side and clamping the heading hierarchy to h4. 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- QA the first 2 documentation practice tabs, still working on the third. 

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

2023-06-23 21:35 UTC, webteam-app commented
Demo starting at https://canonical-com-907.demos.haus

2023-06-23 21:36 UTC, lyubomir-popov commented
@mtruj013 let's sync up about this on Monday to avoid merge conflicts. 
I'll talk to @juanruitina as well.

2023-06-29 15:34 UTC, mtruj013 commented
@juanruitina @lyubomir-popov what do you guys want to do about the side nav on medium and small screens? Since they're on the right in the new design the toggle button ends up on the bottom of the page. Should I hide it on smaller screens, decrease the cols the main content takes up (didn't look great when I tried it), or ? 
![image](https://github.com/canonical/canonical.com/assets/17607612/7ec4ffea-bc18-492d-aafd-7a269d5ee281)

2023-06-29 15:37 UTC, lyubomir-popov commented
> what do you guys want to do about the side nav on medium and small screens? Since they're on the right in the new design the toggle button ends up on the bottom of the page

To get to the bottom of the page, you've already gone past all headings linked to in the sidenav, so to me it can safely be hidden. the page isn't that long anyway

2023-06-29 15:49 UTC, mtruj013 commented
@lyubomir-popov oh agreed, I wasn't suggesting we keep it at the bottom of the page. I was asking if I should make room for it on the grid on med screens so that it isn't at the bottom. I think hiding it is the better option either way though, when I tried making the main content col-medium-4 to make space for the nav on the right it looked pretty bad

2023-06-29 16:59 UTC, juanruitina commented
I agree with hiding the table of contents, there's little content anyway. Some other comments:

- [ ] Header needs some margin on top
- [ ] Tabs have orange accent and a white background, I understand they should be dark gray and transparent instead right? Same with table of contents: the colours need to be adjusted. @lyubomir-popov how are we doing this?
- [ ] "We're hiring" needs some padding on mobile (although I'm not sure how this block should behave there beyond that)
- [ ] There is some horizontal scrolling on mobile, dunno what element's the culprit tho.

2023-06-30 13:48 UTC, mtruj013 commented
Thanks all, I believe I've addressed all your comments. Lyubo's already filed https://github.com/canonical/vanilla-framework/issues/4816 for the z index issue on the sidenav. 

This is ready for all needed reviews, could y'all please take a look? @lyubomir-popov @juanruitina @ClementChaumel

2023-06-30 14:06 UTC, lyubomir-popov commented
Thanks @mtruj013 looks good to me. Note to others - the demo seems to be showing a very outdated version, with orange bar under the selected tabs. Pull locally, works fine there:
![image](https://github.com/canonical/canonical.com/assets/2741678/6556142f-153c-4bca-be47-ed4564d7158c)

2023-06-30 14:28 UTC, juanruitina commented
LGTM :)

2023-06-30 14:28 UTC, juanruitina commented
LGTM :)

2023-07-01 07:20 UTC, anthonydillon commented
This is a comment for design on this one. On small screens the page header looks too close to the top of the page. With a large gap below. Making it look unbalanced: 
![Screenshot_2023-07-01-08-18-02-71_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/canonical/canonical.com/assets/1413534/76729541-758d-4188-8ff1-e09298d5b44a)

Maybe something to work on in the Vanilla typography + block structure @lyubomir-popov

2023-07-03 15:45 UTC, lyubomir-popov commented
> This is a comment for design on this one. On small screens the page header looks too close to the top of the page. With a large gap below. Making it look unbalanced:

@anthonydillon this is an old bug, already fixed - the demo now shows it as it should be:

![image](https://github.com/canonical/canonical.com/assets/2741678/cc3c14c0-fa2f-46e8-9874-c0aa0417d769)

2023-07-03 15:45 UTC, lyubomir-popov commented
@ClementChaumel this is UX+1 and awaiting reviews

2023-07-04 13:19 UTC, mtruj013 requested changes
Thanks @ClementChaumel! A couple of copy changes needed, all pretty minor. There also seems to be a bug with the tabs on the /beyond-canonical, it doesn't set the correct tab as active when clicked. Eg, the active/highlighted tab should be "Encounters and dialog" here
![image](https://github.com/canonical/canonical.com/assets/17607612/f6413cbe-05d6-4281-bbdd-6a3c078aaaee)

2023-07-04 13:19 UTC, mtruj013 commented on templates/documentation/index.html
> -        <p><a href="https://ubuntu.com/blog/the-future-of-documentation-at-canonical">Read about our plan to put these pillars into place at Canonical&nbsp;&rsaquo;</a></p>
This is one is needed as well

2023-07-04 13:19 UTC, mtruj013 commented on templates/documentation/work-and-careers.html
> +        <h2 class="col-3 col-medium-2 p-heading--4 question-heading" id="in-the-documentation-team">In the documentation team?</h2>
```suggestion
        <h2 class="col-3 col-medium-2 p-heading--4 question-heading" id="in-the-documentation-team">In the documentation team</h2>
```

2023-07-04 13:19 UTC, mtruj013 commented on templates/documentation/work-and-careers.html
> +          <p>That is indeed a lot of interviews. It's an in-depth process for an exacting role and we take it very seriously.</p>
I'm confused about this bit and I really wish we had an updated mock-up to work with. On the live site this is separated by an hr, and on the old mock-up it was handled like this:
![image](https://github.com/canonical/canonical.com/assets/17607612/a2c7f391-1932-4ea6-90da-1672972fcb32)

But the new design doesn't seem to make a distinction between this section summary and and the "hiring manager interviews" portion. I think we should at least add an hr, what do you think?

2023-07-04 13:41 UTC, ClementChaumel commented
> Thanks @ClementChaumel! A couple of copy changes needed, all pretty minor. There also seems to be a bug with the tabs on the /beyond-canonical, it doesn't set the correct tab as active when clicked. Eg, the active/highlighted tab should be "Encounters and dialog" here ![image](https://user-images.githubusercontent.com/17607612/250912683-f6413cbe-05d6-4281-bbdd-6a3c078aaaee.png)

I think it's due to the function using an intersection handler to highlight on scroll. It's also happening on live, I'll create an issue

2023-07-05 10:53 UTC, mtruj013 approved these changes
LGTM!

2023-07-05 11:19 UTC, merged