Wd 1174 fix identity and paths
canonical/canonical.com pull request #922
Opened 2023-06-28 09:08 UTC by carkod

## Done

Fix identity and other paths

## QA

- Check these links work as usual:
/careers/company-culture/remote-work
/careers/company-culture/progression
/careers/company-culture/sustainability
/careers/company-culture/diversity
/careers/company-culture

- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4134?atlOrigin=eyJpIjoiNzY0ZDlkYjg5ZmIwNGVhN2JhN2VkNWYxY2M2NTcwYWMiLCJwIjoiaiJ9

2023-06-28 09:08 UTC, webteam-app commented
Demo starting at https://canonical-com-922.demos.haus

2023-07-03 12:24 UTC, anthonydillon requested changes
This route does not work:
https://canonical-com-922.demos.haus/careers/company-culture/progression

2023-07-04 09:18 UTC, anthonydillon approved these changes
Code and QA :+1:. That test cassette is huge!

2023-07-04 14:51 UTC, carkod commented
> Code and QA 👍. That test cassette is huge!

mm I'll try to reduce it.

2023-07-06 10:13 UTC, merged